[project]
name = "samrah"
dynamic = ["version" , "dependencies"] 
description = "An awesome package that does amazing things."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Nadun Udaraka", email = "nadunudaraka@gmail.com" },
]
dependencies = [
    "httpx[http2]",
]
[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"
